from flask import Flask, jsonify
import random

app = Flask(__name__)

HABIT_RECOMMENDATIONS = [
    {"title": "Drink Water", "description": "Stay hydrated by drinking 8 glasses of water daily."},
    {"title": "Morning Stretch", "description": "Start your day with a 5-minute stretching session."},
    {"title": "Read a Book", "description": "Develop your mind by reading at least 20 pages daily."},
    {"title": "Meditation", "description": "Spend 10 minutes meditating to reduce stress."},
    {"title": "Exercise", "description": "Engage in at least 30 minutes of physical activity."},
    {"title": "Sleep Early", "description": "Get at least 7-8 hours of sleep for better health."},
    {"title": "Write a Journal", "description": "Reflect on your day by writing in a journal."},
    {"title": "Learn Something New", "description": "Dedicate time to learning a new skill or topic."},
    {"title": "Take a Walk", "description": "Take a 20-minute walk to refresh your mind."},
    {"title": "Organize Your Space", "description": "Clean or organize your workspace to stay productive."},
    {"title": "Eat Healthy", "description": "Incorporate more fruits and vegetables into your daily meals."},
    {"title": "Practice Gratitude", "description": "List 3 things you're grateful for every morning."},
    {"title": "Limit Screen Time", "description": "Reduce screen time by 30 minutes every day."},
    {"title": "Plan Your Day", "description": "Set clear goals and priorities for the day ahead."},
    {"title": "Socialize", "description": "Spend quality time with friends or family each week."},
    {"title": "Cook a Meal", "description": "Prepare a healthy homemade meal instead of ordering takeout."},
    {"title": "Drink Herbal Tea", "description": "Relax with a cup of herbal tea to reduce stress."},
    {"title": "Practice Yoga", "description": "Engage in a 15-minute yoga session to improve flexibility."},
    {"title": "Track Your Goals", "description": "Keep track of your goals to measure progress."},
    {"title": "Declutter", "description": "Spend 10 minutes decluttering your environment."},
    {"title": "Take Deep Breaths", "description": "Take deep breaths for 5 minutes to calm your mind."},
    {"title": "Avoid Junk Food", "description": "Limit processed and sugary foods for better health."},
    {"title": "Practice Mindfulness", "description": "Take 5 minutes to be mindful and present in the moment."},
    {"title": "Play a Game", "description": "Play a quick game to refresh your mind and relax."},
    {"title": "Go to Bed Early", "description": "Prepare for a restful night's sleep by going to bed early."},
    {"title": "Limit Caffeine", "description": "Reduce your caffeine intake to improve sleep quality."},
    {"title": "Volunteer", "description": "Give back to the community by volunteering for a cause."},
    {"title": "Do a Digital Detox", "description": "Unplug from digital devices for 1 hour each day."},
    {"title": "Laugh", "description": "Watch a funny video or listen to a podcast to lighten your mood."},
    {"title": "Set a Morning Routine", "description": "Establish a positive morning routine to start your day right."},
    {"title": "Listen to Music", "description": "Listen to your favorite music to boost your mood."},
    {"title": "Gardening", "description": "Spend 15 minutes gardening to relax and enjoy nature."},
    {"title": "Morning Walk", "description": "Start your day with a refreshing 20-minute walk."},
    {"title": "Drink Water", "description": "Stay hydrated by drinking 8 glasses of water daily."},
    {"title": "Meditation", "description": "Calm your mind with 10 minutes of meditation daily."},
    {"title": "Gratitude Journal", "description": "Write down three things you’re grateful for every day."},
    {"title": "Workout", "description": "Exercise for at least 30 minutes daily to stay fit."},
    {"title": "Healthy Breakfast", "description": "Kickstart your day with a nutritious meal."},
    {"title": "Learn a New Word", "description": "Expand your vocabulary with a new word daily."},
    {"title": "Plan Your Day", "description": "Spend 5 minutes planning your schedule for the day."},
    {"title": "Save Money", "description": "Set aside a small amount daily to build your savings."},
    {"title": "Read News", "description": "Stay informed by reading the news for 10 minutes daily."},
    {"title": "Stretch", "description": "Improve flexibility with a 5-minute stretching routine."},
    {"title": "Practice Gratitude", "description": "Say thank you to someone or reflect on your blessings."},
    {"title": "Digital Detox", "description": "Avoid screens for 1 hour before bed."},
    {"title": "Eat Fruits", "description": "Add a serving of fruit to your diet every day."},
    {"title": "Positive Affirmations", "description": "Recite three positive affirmations each morning."},
    {"title": "Declutter", "description": "Organize one small area of your home or workspace daily."},
    {"title": "Call a Friend", "description": "Reconnect with someone by calling or messaging them daily."},
    {"title": "Practice a Hobby", "description": "Spend 20 minutes daily on a favorite hobby."},
    {"title": "Learn Something New", "description": "Watch or read something educational for 10 minutes."},
    {"title": "Cook at Home", "description": "Prepare at least one meal at home daily."},
    {"title": "Smile More", "description": "Start your day with a smile to set a positive tone."},
    {"title": "Write a Goal", "description": "Note down one goal you want to achieve today."},
    {"title": "Sleep Early", "description": "Go to bed 30 minutes earlier to improve rest."},
    {"title": "Track Expenses", "description": "Record your daily spending to manage finances better."},
    {"title": "Compliment Someone", "description": "Give a genuine compliment to brighten someone’s day."},
    {"title": "Learn an Instrument", "description": "Practice playing a musical instrument for 15 minutes daily."},
    {"title": "Take Deep Breaths", "description": "Relax with 3-5 deep breaths whenever stressed."},
    {"title": "Volunteer", "description": "Spend time helping others or supporting a cause once a week."},
    {"title": "Limit Sugar", "description": "Reduce your sugar intake with one less sugary item daily."},
    {"title": "Review Goals", "description": "Reflect on your weekly or monthly goals."},
    {"title": "Watch a Documentary", "description": "Expand your knowledge by watching one informative documentary weekly."},
    {"title": "Listen to Podcasts", "description": "Learn and grow by listening to a podcast daily."},
    {"title": "Practice Forgiveness", "description": "Let go of one resentment or grievance daily."},
    {"title": "Drink Green Tea", "description": "Replace a sugary drink with green tea once a day."},
    {"title": "Avoid Junk Food", "description": "Skip one unhealthy meal or snack daily."},
    {"title": "Take Short Breaks", "description": "Take a 5-minute break for every hour of work."},
    {"title": "Learn to Code", "description": "Practice coding for 20 minutes daily."},
    {"title": "Plant Care", "description": "Water and care for your indoor or outdoor plants."},
    {"title": "Avoid Negativity", "description": "Spend 5 minutes reflecting on the positive aspects of your day."},
    {"title": "Daily Gratitude Letter", "description": "Write a short note of thanks to someone important in your life."},
    {"title": "Limit Social Media", "description": "Restrict social media use to 30 minutes daily."},
    {"title": "Daily Prayer", "description": "Spend 5-10 minutes in prayer or reflection."},
    {"title": "Walk After Meals", "description": "Take a short walk after every meal for digestion."},
    {"title": "Study", "description": "Review your notes or read educational material for 30 minutes."},
    {"title": "Keep a Journal", "description": "Write down your thoughts and experiences daily."},
    {"title": "Stand More", "description": "Stand up for 5 minutes every hour to break sedentary habits."},
    {"title": "Mindful Eating", "description": "Avoid distractions while eating to enjoy your meals fully."},
    {"title": "Review Day", "description": "Spend 5 minutes reflecting on what went well and what can improve."},
    {"title": "Daily Drawing", "description": "Draw or sketch something for fun or practice."},
    {"title": "Organize Files", "description": "Sort and clean your digital or physical files daily."},
    {"title": "Cook a New Recipe", "description": "Try cooking a dish you’ve never made before."},
    {"title": "Reduce Clutter", "description": "Get rid of one item you no longer use daily."},
    {"title": "Appreciate Nature", "description": "Spend time outdoors or appreciate a natural scene daily."},
    {"title": "Learn a Language", "description": "Practice a new language for 15 minutes daily."},
    {"title": "Watch Sunrise/Sunset", "description": "Take a moment to watch the sunrise or sunset."},
    {"title": "Public Speaking", "description": "Practice speaking confidently for 5 minutes daily."},
    {"title": "Charity", "description": "Donate a small amount or item weekly to someone in need."},
    {"title": "Read a Blog", "description": "Explore a new topic or interest through blogs daily."},
    {"title": "Practice Yoga", "description": "Perform a 10-minute yoga session daily."},
    {"title": "Compliment Yourself", "description": "Acknowledge one good thing about yourself daily."},
    {"title": "Review Investments", "description": "Check and plan your investments weekly."},
    {"title": "Learn Cooking", "description": "Explore and learn new culinary techniques daily."},
    {"title": "Practice Chess", "description": "Play or practice chess for 10 minutes daily."},
    {"title": "Sing", "description": "Practice singing your favorite song once daily."},
    {"title": "Take a Cold Shower", "description": "Boost your energy with a cold shower daily."},
    {"title": "Avoid Gossip", "description": "Focus on positive conversations daily."},
    {"title": "Practice Mindfulness", "description": "Focus on the present moment for 5 minutes daily."},
    {"title": "Network", "description": "Reach out to one professional contact weekly."},
    {"title": "Share Knowledge", "description": "Teach someone one new thing daily."},
    {"title": "Walk a Pet", "description": "Take your pet for a walk daily to bond and stay active."},
    {"title": "DIY Projects", "description": "Work on one creative project weekly."},
    {"title": "Improve Posture", "description": "Practice sitting and standing with a straight back."},
    {"title": "Write Poetry", "description": "Write a short poem to express your thoughts."},
    {"title": "Reconnect with Family", "description": "Spend quality time with a family member daily."},
    {"title": "Learn Photography", "description": "Take one creative photo daily to improve skills."},
    {"title": "Drink Lemon Water", "description": "Boost metabolism with a glass of lemon water in the morning."},
    {"title": "Learn First Aid", "description": "Learn and practice a basic first aid technique weekly."},
    {"title": "DIY Home Repairs", "description": "Fix or improve something in your home weekly."},
    {"title": "Set a Challenge", "description": "Challenge yourself with one new goal weekly."},
    {"title": "Take a Mental Break", "description": "Spend 5 minutes clearing your mind daily."},
    {"title": "Write a Story", "description": "Add one paragraph to a short story daily."},
    {"title": "Learn Art", "description": "Experiment with painting, sketching, or crafting daily."},
    {"title": "Avoid Procrastination", "description": "Finish one pending task from your to-do list daily."},
    {"title": "Mindful Driving", "description": "Drive attentively without distractions for safety."},
    {"title": "Reduce Plastic", "description": "Replace one plastic item with an eco-friendly alternative daily."},
    {"title": "Learn Public Speaking", "description": "Practice delivering a speech for 5 minutes daily."},
    {"title": "Daily Walks", "description": "Go for a 10-minute stroll to refresh yourself daily."},
    {"title": "Capture Moments", "description": "Take one photo to capture a memory daily."},
    {"title": "Gardening", "description": "Spend 10 minutes tending to plants daily."},
    {"title": "Spend Time Alone", "description": "Reflect on your thoughts and goals for 15 minutes daily."},
    {"title": "Express Gratitude", "description": "Thank someone in person, email, or text daily."},
    {"title": "Study Nature", "description": "Learn one fact about plants or animals daily."},
    {"title": "Balance Work-Life", "description": "Allocate one hour solely for personal growth daily."},
    {"title": "Handwriting Practice", "description": "Write a paragraph to improve handwriting daily."}
    
]    
@app.route('/generate-habit-suggestions', methods=['GET'])
def generate_habit_suggestions():

    suggestions = random.sample(HABIT_RECOMMENDATIONS, 3)
    return jsonify(suggestions)

if __name__ == '__main__':
    app.run(debug=True)